### ISSUE TITLE
CrystalWars v0.6.0控制台报错

### ISSUE THREAD

**Issue by szzz666** [MemoriesOfTime/CrystalWars#42]
2023-05-29 18:05:30.628 [Thread-21] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'CrystalWars v0.6.0-SNAPSHOT': null on cn.lanink.crystalwars.listener.defaults.PlayerJoinAndQuit
2023-05-29 18:05:30.628 [Thread-21] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:18) ~[patched.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:18) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:135) ~[patched.jar:?]
	at cn.nukkit.Player.teleport(Player.java:1379) ~[patched.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:348) ~[patched.jar:?]
	at cc.ruok.tetris.TetrisGame.start(TetrisGame.java:149) ~[?:?]
	at cc.ruok.tetris.commands.TetrisCommand.lambda$execute$0(TetrisCommand.java:40) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "cn.nukkit.level.Level.getFolderName()" because the return value of "cn.nukkit.level.Location.getLevel()" is null
	at cn.lanink.crystalwars.listener.defaults.PlayerJoinAndQuit.onPlayerTp(PlayerJoinAndQuit.java:81) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:15) ~[patched.jar:?]
	... 7 more

**Comment by lt-name** [comment]
Tetris试图将玩家传送到无效世界导致的

**Comment by lt-name** [comment]
更新到最新快照版本

**Comment by szzz666** [comment]
那个...在哪里下载最新快照版本

**Comment by lt-name** [comment]
https://ci.lanink.cn/view/Memories%20Of%20Time/job/CrystalWars/

master是pnx用的
nkx是nkx/pm1e用的

**Comment by szzz666** [comment]
我要收藏这个网站
https://ci.lanink.cn/view/LT_Name/
