### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by szzz666** [MemoriesOfTime/CrystalWars#43]
Nukkit PM1E 1.19.80.2964服务端
MurderMystery v1.4.2-PM1E-SNAPSHOT
是在你的构建站下载的1.4.2版本

[FATAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent' to 'CrystalWars v0.6.0-nkx-SNAPSHOT': null on cn.lanink.crystalwars.listener.defaults.DefaultGameListener 
13:41:32 [ERROR] Throwing 
cn.nukkit.utils.EventException: null 
 at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:18) ~[patched.jar:?] 
 at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:18) ~[patched.jar:?] 
 at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:135) ~[patched.jar:?] 
 at cn.nukkit.block.BlockPressurePlateBase.onEntityCollide(BlockPressurePlateBase.java:21) ~[patched.jar:?] 
 at cn.nukkit.Player.checkBlockCollision(Player.java:1148) ~[patched.jar:?] 
 at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:765) ~[patched.jar:?] 
 at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:44) ~[patched.jar:?] 
 at cn.nukkit.Player.onUpdate(Player.java:2830) ~[patched.jar:?] 
 at cn.nukkit.level.Level.doTick(Level.java:947) ~[patched.jar:?] 
 at cn.nukkit.Server.a(Server.java:1208) ~[patched.jar:?] 
 at cn.nukkit.Server.f(Server.java:150) ~[patched.jar:?] 
 at cn.nukkit.Server.tickProcessor(Server.java:1229) ~[patched.jar:?] 
 at cn.nukkit.Server.start(Server.java:311) ~[patched.jar:?] 
 at cn.nukkit.Server.<init>(Server.java:521) ~[patched.jar:?] 
 at cn.nukkit.Nukkit.main(Nukkit.java:12) ~[patched.jar:?] 
 at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?] 
 at java.lang.Thread.run(Thread.java:833) ~[?:?] 
Caused by: java.lang.NullPointerException: Cannot invoke "cn.nukkit.item.Item.hasCompoundTag()" because "item" is null 
 at cn.lanink.crystalwars.listener.defaults.DefaultGameListener.onPlayerInteract(DefaultGameListener.java:64) ~[?:?] 
 at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?] 
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 
 at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 
 at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:15) ~[patched.jar:?] 
 ... 16 more

**Comment by lt-name** [comment]
已修复

**Comment by szzz666** [comment]
Nukkit PM1E 1.19.80.2964服务端
是在你的构建站下载的
![image](https://github.com/MemoriesOfTime/CrystalWars/assets/60167194/bf9ee07b-22e7-4256-94c7-e1a44a97610b)
这个
退出房间执行命令功能失效
没有报错
